{"id":"v6kw6lwqfc80oao97j9klcb","title":"Quotient with Exception","desc":"","updated":1645562910100,"created":1645562898867,"custom":{},"fname":"ser216.exception-handling.example.quotient-with-exception","type":"note","vault":{"fsPath":"vault"},"contentHash":"09d6aff163f9cf6f644636bb9ed7e4b2","links":[{"from":{"fname":"ser216.exception-handling","vaultName":"vault"},"type":"backlink","position":{"start":{"line":13,"column":5,"offset":359},"end":{"line":13,"column":66,"offset":420},"indent":[]},"value":"ser216.exception-handling.example.quotient-with-exception","alias":"ser216.exception-handling.example.quotient-with-exception"}],"anchors":{},"children":[],"parent":"lN3qf3u1vczxMFQ11oJuC","data":{}}
